export const accessPages = [
  { pageName: "Dashboard", path: "/dashboard" },
  { pageName: "Profile", path: "/profile" },
  { pageName: "Members", path: "/dashboard/members" },
  { pageName: "Add New Member", path: "/dashboard/members/addnew" },
  { pageName: "Medical Info", path: "/dashboard/members/addnew/medical" },
  {
    pageName: "Package Selection",
    path: "/dashboard/members/addnew/package-selection",
  },
  {
    pageName: "Trainer Selection",
    path: "/dashboard/members/addnew/trainer-selection",
  },
  { pageName: "Edit Member", path: "/dashboard/members/edit" },
  { pageName: "Packages", path: "/dashboard/packages" },
  { pageName: "Add Package Type", path: "/dashboard/packages/addpackagetype" },
  { pageName: "All Packages", path: "/dashboard/packages/all-packages" },
  {
    pageName: "Add Packages",
    path: "/dashboard/packages/all-packages/add-packages",
  },
  {
    pageName: "Edit Package",
    path: "/dashboard/packages/all-packages/edit-package",
  },
  {
    pageName: "View Package",
    path: "/dashboard/packages/all-packages/view-package",
  },
  { pageName: "Package Type", path: "/dashboard/packages/package-type" },
  {
    pageName: "Edit Package Type",
    path: "/dashboard/packages/package-type/edit-package-type",
  },
  {
    pageName: "View Package Type",
    path: "/dashboard/packages/package-type/view-package-type",
  },
  { pageName: "Transactions", path: "/dashboard/transactions" },
  { pageName: "Edit Transaction", path: "/dashboard/transactions/edit" },
  { pageName: "Users", path: "/dashboard/users" },
  { pageName: "Add New User", path: "/dashboard/users/addnewuser" },
  { pageName: "Add Staff", path: "/dashboard/users/addnewuser/staff" },
  { pageName: "Add Trainer", path: "/dashboard/users/addnewuser/trainer" },
  { pageName: "Edit User", path: "/dashboard/users/edit" },
  { pageName: "Edit Staff", path: "/dashboard/users/edit/staff" },
  { pageName: "Edit Trainer", path: "/dashboard/users/edit/trainer" },
  { pageName: "View User", path: "/dashboard/users/viewuser" },
  { pageName: "Workouts", path: "/dashboard/workouts" },
  { pageName: "All Schedules", path: "/dashboard/workouts/all-schedules" },
  {
    pageName: "Add Schedule",
    path: "/dashboard/workouts/all-schedules/add-schedule",
  },
  {
    pageName: "Edit Schedule",
    path: "/dashboard/workouts/all-schedules/edit-schedule",
  },
  { pageName: "Exercises", path: "/dashboard/workouts/exercises" },
  { pageName: "Exercises Type", path: "/dashboard/workouts/exercises-type" },
  {
    pageName: "Add Exercises Type",
    path: "/dashboard/workouts/exercises-type/add-exercises-type",
  },
  {
    pageName: "Add Exercises",
    path: "/dashboard/workouts/exercises/add-exercises",
  },
  { pageName: "View Schedules", path: "/dashboard/workouts/view-schedules" },
  {
    pageName: "View Schedule",
    path: "/dashboard/workouts/view-schedules/view-schedule",
  },
  { pageName: "Roles", path: "/dashboard/roles" },
  { pageName: "Add Role", path: "/dashboard/roles/add" },
  { pageName: "Member Schedule", path: "/profile/schedule" },
  { pageName: "Member View", path: "/profile/view" },
  { pageName: "Default", path: "#" },
];
