import type { Metadata } from "next";
import { Geist, Geist_Mono, Poppins } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner";
import JotaiProvider from "./jotai-provider";
import AuthWrapper from "@/components/auth/authWrapper";
import ProtectedLinkWrapper from "@/components/protected-link/protectedLinkWrapper";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={poppins.className}>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <JotaiProvider>
          <AuthWrapper>
            <ProtectedLinkWrapper>
              {children}
              <Toaster />
            </ProtectedLinkWrapper>
          </AuthWrapper>
        </JotaiProvider>
      </body>
    </html>
  );
}
